---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: debian-wheezy-x86
  driver_config:
    box: debian-wheezy-x86
    box_url: https://dl.dropboxusercontent.com/u/17624716/debian-wheezy-x86.box

suites:
- name: default
  run_list: ["recipe[apt]","recipe[crang-jenkins]"]
  attributes: {}
